server:
  port: 7103

eureka:
  client:
    service-url:
      defaultZone: http://Z:Z123@localhost:8761/eureka/

spring:
  application:
    name: hello-service-provider

logging:
  config: classpath:logback.xml
